[package]
name = "fastnoise"
version = "0.1.0"
edition = "2024"

[dependencies]
bracket-color = "0.8.7"
crossterm = "0.29.0"
rand = "0.9.2"
rand_pcg = "0.9.0"
rand_seeder = "0.4.0"
serde = { version = "1.0.228", features = ["derive"] }
