[package]
name = "fastnoise"
version = "0.2.0"
edition = "2024"

[dependencies]
glam = "0.30.9"
rand = "0.9.2"
rand_pcg = "0.9.0"
rand_seeder = "0.4.0"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
