[package]
name = "fastnoise"
version = "0.3.2"
edition = "2024"

[dependencies]
glam = "0.30.9"
rand = "0.9.2"
rand_pcg = "0.9.0"
rand_seeder = "0.4.0"
rayon = { version = "1.11.0", optional = true }
serde = { version = "1.0.228", features = ["derive"] }

[features]
sampler = ["rayon"]
